version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ecom_db
    environment:
      MYSQL_ROOT_PASSWORD: Bksra99@
      MYSQL_DATABASE: ecom_db
    ports:
      - "3306:3306"
    networks:
      - ecom-network

  backend:
    image: ecomregistry743.azurecr.io/order-backend:v1
    container_name: order-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecom_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bksra99@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    networks:
      - ecom-network

  frontend:
    image: ecomregistry743.azurecr.io/ecom-frontend:v1
    container_name: order-frontend
    ports:
      - "80:80"
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge
